### ISSUE TITLE
Compute weighted means of 51 regions by internet traffic or population

### ISSUE THREAD

**Issue by tangaw** [Badwater-Apps/ethnic-cuisine-trends#1]
Will result in two CSVs:

- [x] One raw file

- [x] One aggregated file

**Comment by dongskyler** [comment]
Please generate CSV files of the arithmetic mean and the weighted mean as a function of time. I'd like to plot both set of numbers.

**Comment by tangaw** [comment]
### Update
I've sifted through a couple options for data pertaining to **internet access/use by state (USA)**, and am currently down to two data sources for reference:
1. [NCES.GOV](https://nces.ed.gov/programs/digest/d18/tables/dt18_702.60.asp?current=yes)
2. [NTIA.GOV](https://www.ntia.doc.gov/data/digital-nation-data-explorer#sel=internetUser&disp=map)

Both seem like reputable sources and have data sets available for download. I haven't decided on which one to use, though I am leaning towards the latter due to the plethora of metrics provided in the drop-down menu.
### Questions:
- What is our take on `households with internet access` VS. `internet use (anywhere)` as our go-to metric? (This difference is illustrated between the two links provided as well as within the latter link itself)
- As opposed to using the most current data (2017) for all dates from 2004 to 2020, do we want to go the extra mile of calculating weighted means by the **latest available data at the time**? (e.g. using 2017 data for years 2017-2020, 2015 data for years 2015-2016 etc.)

**Comment by dongskyler** [comment]
> I like the latter, NITA.gov. 

It’s simpler for our purpose. I think it can save us some time. 

How long will the extra of mile of using time-dependent weights cost you? 5 hours? 

> I **don’t** think using time-dependent weights is worth it at this juncture. 

We can use the latest data for all time (2004-2020). Although the national percentage of internet users increased from ~60% to ~80%, most state-level data also increased from ~60% to ~80%. That means, normalized state-level weights may not be that different over time. 

We can always go back and calculate time-dependent weights, if you see the need in the future. But now, I think our time is far more valuable.

**Comment by tangaw** [comment]
Time-dependent weights will probably require an additional method or a few extra lines within the existing one. We can put a pin on that.

By the way, are we really measuring our time in terms of hours? XD

**Comment by dongskyler** [comment]
> Time-dependent weights will probably require an additional method or a few extra lines within the existing one. We can put a pin on that.
> 
> By the way, are we really measuring our time in terms of hours? XD

Let's create an issue ticket and put a pin on it. 

What do you mean by "measuring our time in hours"?

**Comment by tangaw** [comment]
> How long will the extra of mile of using time-dependent weights cost you? 5 hours?

I was referring to this comment. 5 hours seems like an awfully specific time frame is all.

**Comment by dongskyler** [comment]
> > How long will the extra of mile of using time-dependent weights cost you? 5 hours?
> 
> I was referring to this comment. 5 hours seems like an awfully specific time frame is all.

I see. I was going for some measure that is more informative rather than specific. 

5 hours is pretty much a day's work.
